server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testing
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    edu:
      hillel:
        lesson38: INFO
    org:
      springframework:
        web: INFO
  file:
    name: lesson38.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"