server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true

logging:
  level:
    edu:
      hillel:
        lesson35: INFO
    org:
      springframework:
        web: INFO
  file:
    name: lesson35.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

security:
  basic:
    enabled: true

